### ISSUE TITLE
Fill on white background

### ISSUE THREAD

**Issue by timo002** [williammalone/HTML5-Paint-Bucket-Tool#4]
@williammalone,

The script now only fills the all transparent space, but what should be changed to get it also working for any color that is clicked? Or for example, if I use white area's that must be filled. I think this is a minor tweak in the code, but can't find it.

Thanks in advance!

**Comment by williammalone** [comment]
Hi timo002,

  The example code for the bucket tool has two layers: a color layer (where the colors are drawn) and an outline layer (the black and transparent image i.e. the watermelon duck which is not changed).  The two layers are stacked on top of each other so that we can draw to the color layer and keep the outline smooth and anti-aliased.  The color layer will fill in any contiguous pixels once tapped, but since it starts off empty you would need to draw to the color layer initially.  Just create a new variable for the initial color image and assign it an "src" property with the image path and an "onload" property with a function that draws to the context (like the outlineImage in the init function).  Note: You will also need to change the outlineImage.onload function since it clears the canvas if it loads after the new onload function.

  Let me know if this is what you are looking for and it works for you.

**Comment by timo002** [comment]
Hello William,

I can work with this! Thanks!
